### ISSUE TITLE
Problem building drivers on 4.19.29 kernel -   init_timer issues

### ISSUE THREAD

**Issue by dbrb2** [lixinswitchpi/oak#2]
It looks like   init_timer has been deprecated in the latest kernel? See below....

pi@raspberrypi:~ $ cd /usr/src/dahdi-linux-oak-2.11.1/
pi@raspberrypi:/usr/src/dahdi-linux-oak-2.11.1 $ make
make -C drivers/dahdi/firmware firmware-loaders
make[1]: Entering directory '/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/firmware'
make[1]: Leaving directory '/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/firmware'
make -C /lib/modules/4.19.29-v7+/build SUBDIRS=/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi DAHDI_INCLUDE=/usr/src/dahdi-linux-oak-2.11.1/include DAHDI_MODULES_EXTRA=" " HOTPLUG_FIRMWARE=yes modules DAHDI_BUILD_ALL=m
make[1]: Entering directory '/home/pi/linux'
/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/Kbuild:125: CPU Architecture 'arm' does not support VPMADT032 or HPEC. Skipping.
  HOSTCC  /usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/print_fxo_modes.o
  HOSTLD  /usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/print_fxo_modes
  GEN     /usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/init_fxo_modes
  CC [M]  /usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/xbus-core.o
/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/xbus-core.c: In function ‘xbus_new’:
/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/xbus-core.c:1615:2: error: implicit declaration of function ‘init_timer’ [-Werror=implicit-function-declaration]
  init_timer(&xbus->command_timer);
  ^~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target '/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/xbus-core.o' failed
make[3]: *** [/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp/xbus-core.o] Error 1
scripts/Makefile.build:544: recipe for target '/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp' failed
make[2]: *** [/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi/xpp] Error 2
Makefile:1520: recipe for target '_module_/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi' failed
make[1]: *** [_module_/usr/src/dahdi-linux-oak-2.11.1/drivers/dahdi] Error 2
make[1]: Leaving directory '/home/pi/linux'
Makefile:74: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by wrljet** [comment]
init_timer was deprecated with Linux 4.15.

**Comment by dbrb2** [comment]
Yep - so for now I am building using a (slightly) older kernel, but it would be nice to be able to use more recent kernels at some point in the future

**Comment by wrljet** [comment]
This problem is in the official Dahdi sources as well.
It starts to have trouble compiling after Linux 4.11.0.

Switchpi's Dahdi Thunder has mods that work with 4.14, but evidently they haven't done that with this oak version.

-Bill

**Comment by antonatosn** [comment]
I solve the issue using the latest DAHDI drivers

**Comment by bf** [comment]
@antonatosn Can you please give us a bit more info on how you resolved this issue?

Which version of dahdi drivers did you use? Did they work out of the box with the SwitchPI appliance or did you have to recompile the kernel as well?

**Comment by antonatosn** [comment]
Hi, This is an old try that I did. I use dahdi 3.1.0. If you want to solve the issue check the oakpro and just replace the drivers on oak folder and on Kbuild.
OAKPRO uses 2.11.1, use that
